services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - 127.0.0.1:5432:5432

volumes:
  db-data: {}
